version: "3.8"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_SECRET_KEY_EXPIRE_MINUTES_COUNT: ${JWT_SECRET_KEY_EXPIRE_MINUTES_COUNT}
      TELEGRAM_BOT_KEY: ${TELEGRAM_BOT_KEY}
      BASIC_AUTH_TOKEN: ${BASIC_AUTH_TOKEN}
    depends_on:
      - postgres
    networks:
      - bridge_network

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    depends_on:
      - app
    networks:
      - bridge_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - bridge_network

  # metabase:
  #   image: metabase/metabase
  #   ports:
  #     - "3000:3000" 
  #   environment:
  #     - MB_DB_TYPE=postgres
  #     - MB_DB_DBNAME=${POSTGRES_DB}
  #     - MB_DB_PORT=${POSTGRES_PORT}
  #     - MB_DB_USER=${POSTGRES_USER}
  #     - MB_DB_PASS=${POSTGRES_PASSWORD}
  #     - MB_DB_HOST=${POSTGRES_HOST}
  #   depends_on:
  #     - postgres

networks:
  bridge_network:
    driver: bridge

