version: '3.8'

services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_SECRET_KEY_EXPIRE_MINUTES_COUNT: ${JWT_SECRET_KEY_EXPIRE_MINUTES_COUNT}
      TELEGRAM_BOT_KEY: ${TELEGRAM_BOT_KEY}
      BASIC_AUTH_TOKEN: ${BASIC_AUTH_TOKEN}
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"